import Head from "next/head";
import Image from "next/image";
import { name, about, bio, avatar, passion } from "../lib/info";
import { Box, Heading, Text, useColorMode, Flex } from "@chakra-ui/react";
import { MotionBox } from "@/utils/motion";

export const revalidate = 60;

const variants = {
  hidden: { opacity: 0, x: -200, y: 0 },
  enter: { opacity: 1, x: 0, y: 0 },
  exit: { opacity: 0, x: 0, y: -100 },
};

export default function Home() {
  const { colorMode, setColorMode } = useColorMode();
  return (
    <>
      <Head>
        <title>Kaushik Ravikumar | Full Stack Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <MotionBox
        as="section"
        initial="hidden"
        animate="enter"
        exit="exit"
        variants={variants}
        transition={{ type: "linear" }}
      >
        <Heading fontSize={"3xl"} fontWeight="bold">
          {name}
        </Heading>
        <Text
          marginY={"1.25rem"}
          color={colorMode === "light" ? "text.100" : "text.200"}
        >
          {about()}
        </Text>
        <Flex
          alignItems={["start", "center"]}
          marginY="2rem"
          flexDir={["row", "row", "row"]}
        >
          <Image
            alt={name}
            style={{
              borderRadius: "100%",
            }}
            src={avatar}
            placeholder="blur"
            width={100}
            priority
          />
        </Flex>
        <Box color={colorMode === "light" ? "text.100" : "text.200"}>
          <Text lineHeight={"2rem"} mb="1rem">
            {bio()}
          </Text>
          <hr />
          <Text mt={"1.5rem"} lineHeight={"2rem"}>
            {passion()}
          </Text>
        </Box>
      </MotionBox>
    </>
  );
}
